name: PR Branch Labeler

on:
  pull_request:
    types: [opened]

jobs:
  label_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: nrccua/pr-branch-labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
